name: "publish"

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: ubuntu-22.04
            args: "--verbose"
            target: "linux"
          - platform: windows-latest
            args: "--verbose"
            target: "windows"
          - platform: macos-latest
            args: "--target x86_64-apple-darwin"
            target: "macos-intel"
          - platform: macos-latest
            args: "--target aarch64-apple-darwin"
            target: "macos-arm"

    runs-on: ${{ matrix.settings.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Add Rust targets(macOS)
        if: matrix.settings.target == 'macos-arm'
        run: rustup target add aarch64-apple-darwin

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
          components: rust-src

      - name: install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: latest

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.settings.args }}
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
